name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    environment: 
      name: production   # aa
    steps:
      - run: echo "This is a pen"
      - uses: actions/checkout@v2
      - run: |
          ls -al
          cd .github/workflows/
          ls -al
      - run: |
          echo ${{ secrets.PROJECT_ID }} >> .env
          ls -al
          cat .env
      - run: |
          echo ${{ secrets.APP_ID }}
